apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployment-management
  namespace: argocd
  # Not using ArgoCD finalizer since it will deadlock if the app is deleted
  finalizers:
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: /
    repoURL: https://github.com/npflan/argocd.git
    targetRevision: master
