apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  # Not using ArgoCD finalizer since it will deadlock if the app is deleted
  finalizers:
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.10
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
