apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Containing all cluster infrastructure components
  sourceRepos:
  - "*"
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: dhcp
    server: https://kubernetes.default.svc
  - namespace: prometheus
    server: https://kubernetes.default.svc
  - namespace: dns
    server: https://kubernetes.default.svc
  - namespace: kube-eagle
    server: https://kubernetes.default.svc
  - namespace: grafana
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
